org: rockinliam
app: news-ai
service: news-server

custom:
    stage: ${opt:stage, self:provider.stage}
    profile:
        dev: news-server
    apiRoot: api/1
    webpack:
        includeModules: true
    dynamodb:
        start:
            migrate: true
        stages:
            - dev
    reqValidatorName: request-validator
    bucket: headlines-bucket

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    logRetentionInDays: 1
    region: eu-west-2
    iamRoleStatements:
        - Effect: 'Allow'
          Action:
              - 'dynamodb:*'
              - 's3:*'
          Resource: '*'
    apiGateway:
    binaryMediaTypes:
        - '*/*'
    versionFunctions: true

package:
    include:
        - .build/src/**
    exclude:
        - .build
        - '.*/__tests__/**'
        - 'src/**'
        - 'coverage/**'
        - 'tests/**'

functions:
    getHeadlines:
        handler: src/lambdas/getHeadlines.handler
        timeout: 10
        events:
            - http:
                  cors: true
                  private: false
                  method: get
                  path: headlines
        provisionedConcurrency: 5

    buildHeadlines:
        handler: src/lambdas/buildHeadlines.handler
        timeout: 900
        events:
            - http:
                  cors: true
                  private: false
                  method: get
                  path: build
            - schedule:
                  rate: rate(30 minutes)
        provisionedConcurrency: 2

resources:
    Resources:
        CustomRequestValidator:
            Type: 'AWS::ApiGateway::RequestValidator'
            Properties:
                # Name: 'cust-req-validator'
                Name: ${self:custom.reqValidatorName}
                RestApiId:
                    Ref: ApiGatewayRestApi
                ValidateRequestBody: true
                ValidateRequestParameters: true
        S3HeadlinesBucket:
            Type: 'AWS::S3::Bucket'
            Properties:
                BucketName: ${self:custom.bucket}

plugins:
    - serverless-plugin-ts-validation
    - serverless-webpack
    - serverless-reqvalidator-plugin
    - serverless-dynamodb-local
    - serverless-offline
